// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lurus/events/v1/annotations.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_lurus_events_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50100,
		Name:          "lurus.events.v1.pii",
		Tag:           "varint,50100,opt,name=pii",
		Filename:      "lurus/events/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Marks a payload field as personal data (PII).
	//
	// Every PII field in an event payload MUST carry this option (see
	// SCHEMA_RULES.md). Reserved for future crypto-shredding: PII fields will be
	// encrypted with a per-tenant key so that deleting the key erases the data
	// across the otherwise immutable event log.
	//
	// optional bool pii = 50100;
	E_Pii = &file_lurus_events_v1_annotations_proto_extTypes[0]
)

var File_lurus_events_v1_annotations_proto protoreflect.FileDescriptor

const file_lurus_events_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"!lurus/events/v1/annotations.proto\x12\x0flurus.events.v1\x1a google/protobuf/descriptor.proto:1\n" +
	"\x03pii\x12\x1d.google.protobuf.FieldOptions\x18\xb4\x87\x03 \x01(\bR\x03piiB>Z<github.com/hanmahong5-arch/lurus-proto-go/events/v1;eventsv1b\x06proto3"

var file_lurus_events_v1_annotations_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_lurus_events_v1_annotations_proto_depIdxs = []int32{
	0, // 0: lurus.events.v1.pii:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lurus_events_v1_annotations_proto_init() }
func file_lurus_events_v1_annotations_proto_init() {
	if File_lurus_events_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lurus_events_v1_annotations_proto_rawDesc), len(file_lurus_events_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_lurus_events_v1_annotations_proto_goTypes,
		DependencyIndexes: file_lurus_events_v1_annotations_proto_depIdxs,
		ExtensionInfos:    file_lurus_events_v1_annotations_proto_extTypes,
	}.Build()
	File_lurus_events_v1_annotations_proto = out.File
	file_lurus_events_v1_annotations_proto_goTypes = nil
	file_lurus_events_v1_annotations_proto_depIdxs = nil
}
