// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lurus/events/v1/deadletter.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeadLetter is the pointer record a projector publishes when an event
// exhausts its retries or cannot be decoded. It REFERENCES the event in the
// authoritative log — never copies it: the log keeps the only original, and
// re-drive tooling resolves (stream, stream_seq) back to the wire bytes.
//
// This is infrastructure, not a business event: it is not in the event-type
// registry and carries no EventEnvelope. It still lives here (not as ad-hoc
// JSON) so DLQ consumers in any language get the same buf-governed,
// breaking-change-protected contract as everything else on the backbone.
type DeadLetter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream holding the dead event.
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// The dead event's authoritative stream sequence.
	StreamSeq uint64 `protobuf:"varint,2,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	// Subject the event was published on.
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// Durable consumer (projector) that gave up.
	Durable string `protobuf:"bytes,4,opt,name=durable,proto3" json:"durable,omitempty"`
	// Envelope event_id; empty when the envelope was undecodable.
	EventId string `protobuf:"bytes,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Envelope event_type; "<undecodable>" for poison bytes.
	EventType string `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Why it was dead-lettered: "exhausted" or "poison".
	Cause string `protobuf:"bytes,7,opt,name=cause,proto3" json:"cause,omitempty"`
	// Last apply/unmarshal error, for humans.
	Error string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// Delivery attempts consumed before giving up.
	NumDelivered uint64 `protobuf:"varint,9,opt,name=num_delivered,json=numDelivered,proto3" json:"num_delivered,omitempty"`
	// When the pointer was written.
	DeadLetteredAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=dead_lettered_at,json=deadLetteredAt,proto3" json:"dead_lettered_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeadLetter) Reset() {
	*x = DeadLetter{}
	mi := &file_lurus_events_v1_deadletter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetter) ProtoMessage() {}

func (x *DeadLetter) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_v1_deadletter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetter.ProtoReflect.Descriptor instead.
func (*DeadLetter) Descriptor() ([]byte, []int) {
	return file_lurus_events_v1_deadletter_proto_rawDescGZIP(), []int{0}
}

func (x *DeadLetter) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *DeadLetter) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *DeadLetter) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *DeadLetter) GetDurable() string {
	if x != nil {
		return x.Durable
	}
	return ""
}

func (x *DeadLetter) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeadLetter) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *DeadLetter) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *DeadLetter) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeadLetter) GetNumDelivered() uint64 {
	if x != nil {
		return x.NumDelivered
	}
	return 0
}

func (x *DeadLetter) GetDeadLetteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeadLetteredAt
	}
	return nil
}

var File_lurus_events_v1_deadletter_proto protoreflect.FileDescriptor

const file_lurus_events_v1_deadletter_proto_rawDesc = "" +
	"\n" +
	" lurus/events/v1/deadletter.proto\x12\x0flurus.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x02\n" +
	"\n" +
	"DeadLetter\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x02 \x01(\x04R\tstreamSeq\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\adurable\x18\x04 \x01(\tR\adurable\x12\x19\n" +
	"\bevent_id\x18\x05 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12\x14\n" +
	"\x05cause\x18\a \x01(\tR\x05cause\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12#\n" +
	"\rnum_delivered\x18\t \x01(\x04R\fnumDelivered\x12D\n" +
	"\x10dead_lettered_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0edeadLetteredAtB>Z<github.com/hanmahong5-arch/lurus-proto-go/events/v1;eventsv1b\x06proto3"

var (
	file_lurus_events_v1_deadletter_proto_rawDescOnce sync.Once
	file_lurus_events_v1_deadletter_proto_rawDescData []byte
)

func file_lurus_events_v1_deadletter_proto_rawDescGZIP() []byte {
	file_lurus_events_v1_deadletter_proto_rawDescOnce.Do(func() {
		file_lurus_events_v1_deadletter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lurus_events_v1_deadletter_proto_rawDesc), len(file_lurus_events_v1_deadletter_proto_rawDesc)))
	})
	return file_lurus_events_v1_deadletter_proto_rawDescData
}

var file_lurus_events_v1_deadletter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lurus_events_v1_deadletter_proto_goTypes = []any{
	(*DeadLetter)(nil),            // 0: lurus.events.v1.DeadLetter
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_lurus_events_v1_deadletter_proto_depIdxs = []int32{
	1, // 0: lurus.events.v1.DeadLetter.dead_lettered_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lurus_events_v1_deadletter_proto_init() }
func file_lurus_events_v1_deadletter_proto_init() {
	if File_lurus_events_v1_deadletter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lurus_events_v1_deadletter_proto_rawDesc), len(file_lurus_events_v1_deadletter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lurus_events_v1_deadletter_proto_goTypes,
		DependencyIndexes: file_lurus_events_v1_deadletter_proto_depIdxs,
		MessageInfos:      file_lurus_events_v1_deadletter_proto_msgTypes,
	}.Build()
	File_lurus_events_v1_deadletter_proto = out.File
	file_lurus_events_v1_deadletter_proto_goTypes = nil
	file_lurus_events_v1_deadletter_proto_depIdxs = nil
}
