// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lurus/events/v1/envelope.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorType int32

const (
	ActorType_ACTOR_TYPE_UNSPECIFIED ActorType = 0
	ActorType_ACTOR_TYPE_USER        ActorType = 1
	ActorType_ACTOR_TYPE_SERVICE     ActorType = 2
	ActorType_ACTOR_TYPE_SYSTEM      ActorType = 3
)

// Enum value maps for ActorType.
var (
	ActorType_name = map[int32]string{
		0: "ACTOR_TYPE_UNSPECIFIED",
		1: "ACTOR_TYPE_USER",
		2: "ACTOR_TYPE_SERVICE",
		3: "ACTOR_TYPE_SYSTEM",
	}
	ActorType_value = map[string]int32{
		"ACTOR_TYPE_UNSPECIFIED": 0,
		"ACTOR_TYPE_USER":        1,
		"ACTOR_TYPE_SERVICE":     2,
		"ACTOR_TYPE_SYSTEM":      3,
	}
)

func (x ActorType) Enum() *ActorType {
	p := new(ActorType)
	*p = x
	return p
}

func (x ActorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorType) Descriptor() protoreflect.EnumDescriptor {
	return file_lurus_events_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (ActorType) Type() protoreflect.EnumType {
	return &file_lurus_events_v1_envelope_proto_enumTypes[0]
}

func (x ActorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorType.Descriptor instead.
func (ActorType) EnumDescriptor() ([]byte, []int) {
	return file_lurus_events_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// EventEnvelope is the single wire format for every event on the lurus event
// backbone (one append-only authoritative log, N independently materialized
// read views). The payload is an opaque serialized protobuf message whose
// concrete type is named by event_type.
type EventEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ULID (26-char Crockford base32, monotonic within an emitter). Doubles as
	// the JetStream Nats-Msg-Id dedup key.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// NSID-style event type, e.g. "cn.lurus.tally.stock.received". A type name
	// is never reused with different semantics: a semantic change is a NEW type
	// (see SCHEMA_RULES.md).
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Version of the payload schema for this event_type. Starts at 1; bumped
	// only on additive payload changes.
	SchemaVer uint32 `protobuf:"varint,3,opt,name=schema_ver,json=schemaVer,proto3" json:"schema_ver,omitempty"`
	// Owning tenant. Empty only for platform-global events.
	TenantId string `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Who caused the event.
	Actor *Actor `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`
	// Business time: when the fact became true (not when it was published).
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Serialized payload message of the type named by event_type / schema_ver.
	Payload []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// Lowercase hex SHA-256 of the previous envelope's canonical bytes on the
	// same subject; "" for the first event. Forms a per-subject hash chain for
	// tamper evidence (see ADR 003 in eventkit).
	PrevHash string `protobuf:"bytes,8,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	// W3C trace id for cross-service correlation. Optional.
	TraceId       string `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_lurus_events_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_lurus_events_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetSchemaVer() uint32 {
	if x != nil {
		return x.SchemaVer
	}
	return 0
}

func (x *EventEnvelope) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EventEnvelope) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *EventEnvelope) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *EventEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// Actor identifies the principal that caused an event.
type Actor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ActorType              `protobuf:"varint,1,opt,name=type,proto3,enum=lurus.events.v1.ActorType" json:"type,omitempty"`
	// User id, service name, or job name depending on type.
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_lurus_events_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_lurus_events_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Actor) GetType() ActorType {
	if x != nil {
		return x.Type
	}
	return ActorType_ACTOR_TYPE_UNSPECIFIED
}

func (x *Actor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_lurus_events_v1_envelope_proto protoreflect.FileDescriptor

const file_lurus_events_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1elurus/events/v1/envelope.proto\x12\x0flurus.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x02\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"schema_ver\x18\x03 \x01(\rR\tschemaVer\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12,\n" +
	"\x05actor\x18\x05 \x01(\v2\x16.lurus.events.v1.ActorR\x05actor\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x1b\n" +
	"\tprev_hash\x18\b \x01(\tR\bprevHash\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\"G\n" +
	"\x05Actor\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.lurus.events.v1.ActorTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id*k\n" +
	"\tActorType\x12\x1a\n" +
	"\x16ACTOR_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACTOR_TYPE_USER\x10\x01\x12\x16\n" +
	"\x12ACTOR_TYPE_SERVICE\x10\x02\x12\x15\n" +
	"\x11ACTOR_TYPE_SYSTEM\x10\x03B>Z<github.com/hanmahong5-arch/lurus-proto-go/events/v1;eventsv1b\x06proto3"

var (
	file_lurus_events_v1_envelope_proto_rawDescOnce sync.Once
	file_lurus_events_v1_envelope_proto_rawDescData []byte
)

func file_lurus_events_v1_envelope_proto_rawDescGZIP() []byte {
	file_lurus_events_v1_envelope_proto_rawDescOnce.Do(func() {
		file_lurus_events_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lurus_events_v1_envelope_proto_rawDesc), len(file_lurus_events_v1_envelope_proto_rawDesc)))
	})
	return file_lurus_events_v1_envelope_proto_rawDescData
}

var file_lurus_events_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lurus_events_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lurus_events_v1_envelope_proto_goTypes = []any{
	(ActorType)(0),                // 0: lurus.events.v1.ActorType
	(*EventEnvelope)(nil),         // 1: lurus.events.v1.EventEnvelope
	(*Actor)(nil),                 // 2: lurus.events.v1.Actor
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_lurus_events_v1_envelope_proto_depIdxs = []int32{
	2, // 0: lurus.events.v1.EventEnvelope.actor:type_name -> lurus.events.v1.Actor
	3, // 1: lurus.events.v1.EventEnvelope.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 2: lurus.events.v1.Actor.type:type_name -> lurus.events.v1.ActorType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_lurus_events_v1_envelope_proto_init() }
func file_lurus_events_v1_envelope_proto_init() {
	if File_lurus_events_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lurus_events_v1_envelope_proto_rawDesc), len(file_lurus_events_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lurus_events_v1_envelope_proto_goTypes,
		DependencyIndexes: file_lurus_events_v1_envelope_proto_depIdxs,
		EnumInfos:         file_lurus_events_v1_envelope_proto_enumTypes,
		MessageInfos:      file_lurus_events_v1_envelope_proto_msgTypes,
	}.Build()
	File_lurus_events_v1_envelope_proto = out.File
	file_lurus_events_v1_envelope_proto_goTypes = nil
	file_lurus_events_v1_envelope_proto_depIdxs = nil
}
