// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lurus/events/lugo/v1/billing.proto

package lugoeventsv1

import (
	_ "github.com/hanmahong5-arch/lurus-proto-go/events/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LedgerKind int32

const (
	LedgerKind_LEDGER_KIND_UNSPECIFIED LedgerKind = 0
	// Token-quota ledger (platform ledger Kind 1).
	LedgerKind_LEDGER_KIND_QUOTA LedgerKind = 1
	// Cash-wallet mirror ledger, unit = fen (platform ledger Kind 2).
	LedgerKind_LEDGER_KIND_CREDITS LedgerKind = 2
)

// Enum value maps for LedgerKind.
var (
	LedgerKind_name = map[int32]string{
		0: "LEDGER_KIND_UNSPECIFIED",
		1: "LEDGER_KIND_QUOTA",
		2: "LEDGER_KIND_CREDITS",
	}
	LedgerKind_value = map[string]int32{
		"LEDGER_KIND_UNSPECIFIED": 0,
		"LEDGER_KIND_QUOTA":       1,
		"LEDGER_KIND_CREDITS":     2,
	}
)

func (x LedgerKind) Enum() *LedgerKind {
	p := new(LedgerKind)
	*p = x
	return p
}

func (x LedgerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_lurus_events_lugo_v1_billing_proto_enumTypes[0].Descriptor()
}

func (LedgerKind) Type() protoreflect.EnumType {
	return &file_lurus_events_lugo_v1_billing_proto_enumTypes[0]
}

func (x LedgerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerKind.Descriptor instead.
func (LedgerKind) EnumDescriptor() ([]byte, []int) {
	return file_lurus_events_lugo_v1_billing_proto_rawDescGZIP(), []int{0}
}

// TransferRef mirrors the platform ledger's 128-bit application-generated
// transfer id. Replaying an event with a TransferRef the ledger has already
// applied is a no-op there (StatusExists), which is what makes these events
// safe to re-consume.
type TransferRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hi            uint64                 `protobuf:"varint,1,opt,name=hi,proto3" json:"hi,omitempty"`
	Lo            uint64                 `protobuf:"varint,2,opt,name=lo,proto3" json:"lo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRef) Reset() {
	*x = TransferRef{}
	mi := &file_lurus_events_lugo_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRef) ProtoMessage() {}

func (x *TransferRef) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_lugo_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRef.ProtoReflect.Descriptor instead.
func (*TransferRef) Descriptor() ([]byte, []int) {
	return file_lurus_events_lugo_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRef) GetHi() uint64 {
	if x != nil {
		return x.Hi
	}
	return 0
}

func (x *TransferRef) GetLo() uint64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

// BillingCharged: a wallet was charged for a product order.
type BillingCharged struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TransferId *TransferRef           `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	WalletId   string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	// Must be > 0. Fen for LEDGER_KIND_CREDITS; tokens for LEDGER_KIND_QUOTA.
	Amount        int64      `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Ledger        LedgerKind `protobuf:"varint,4,opt,name=ledger,proto3,enum=lurus.events.lugo.v1.LedgerKind" json:"ledger,omitempty"`
	ProductCode   string     `protobuf:"bytes,5,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	OrderId       string     `protobuf:"bytes,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingCharged) Reset() {
	*x = BillingCharged{}
	mi := &file_lurus_events_lugo_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingCharged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingCharged) ProtoMessage() {}

func (x *BillingCharged) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_lugo_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingCharged.ProtoReflect.Descriptor instead.
func (*BillingCharged) Descriptor() ([]byte, []int) {
	return file_lurus_events_lugo_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *BillingCharged) GetTransferId() *TransferRef {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *BillingCharged) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *BillingCharged) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BillingCharged) GetLedger() LedgerKind {
	if x != nil {
		return x.Ledger
	}
	return LedgerKind_LEDGER_KIND_UNSPECIFIED
}

func (x *BillingCharged) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *BillingCharged) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// BillingRefunded: a previous charge was (partially) reversed.
type BillingRefunded struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TransferId *TransferRef           `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	WalletId   string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	// Must be > 0; same unit rules as BillingCharged.
	Amount int64      `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Ledger LedgerKind `protobuf:"varint,4,opt,name=ledger,proto3,enum=lurus.events.lugo.v1.LedgerKind" json:"ledger,omitempty"`
	// The order whose charge is being reversed.
	OriginalOrderId string `protobuf:"bytes,5,opt,name=original_order_id,json=originalOrderId,proto3" json:"original_order_id,omitempty"`
	// Human-entered refund reason — free text can carry person names, hence
	// PII (SCHEMA_RULES R5).
	Reason        string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingRefunded) Reset() {
	*x = BillingRefunded{}
	mi := &file_lurus_events_lugo_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingRefunded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingRefunded) ProtoMessage() {}

func (x *BillingRefunded) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_lugo_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingRefunded.ProtoReflect.Descriptor instead.
func (*BillingRefunded) Descriptor() ([]byte, []int) {
	return file_lurus_events_lugo_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *BillingRefunded) GetTransferId() *TransferRef {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *BillingRefunded) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *BillingRefunded) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BillingRefunded) GetLedger() LedgerKind {
	if x != nil {
		return x.Ledger
	}
	return LedgerKind_LEDGER_KIND_UNSPECIFIED
}

func (x *BillingRefunded) GetOriginalOrderId() string {
	if x != nil {
		return x.OriginalOrderId
	}
	return ""
}

func (x *BillingRefunded) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// QuotaDeducted: metered usage consumed token quota (hot path fact).
type QuotaDeducted struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TransferId *TransferRef           `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	WalletId   string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	// Tokens deducted; must be > 0.
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Usage record / request id that caused the deduction.
	RefId         string `protobuf:"bytes,4,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaDeducted) Reset() {
	*x = QuotaDeducted{}
	mi := &file_lurus_events_lugo_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaDeducted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaDeducted) ProtoMessage() {}

func (x *QuotaDeducted) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_lugo_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaDeducted.ProtoReflect.Descriptor instead.
func (*QuotaDeducted) Descriptor() ([]byte, []int) {
	return file_lurus_events_lugo_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *QuotaDeducted) GetTransferId() *TransferRef {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *QuotaDeducted) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *QuotaDeducted) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *QuotaDeducted) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

var File_lurus_events_lugo_v1_billing_proto protoreflect.FileDescriptor

const file_lurus_events_lugo_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\"lurus/events/lugo/v1/billing.proto\x12\x14lurus.events.lugo.v1\x1a!lurus/events/v1/annotations.proto\"-\n" +
	"\vTransferRef\x12\x0e\n" +
	"\x02hi\x18\x01 \x01(\x04R\x02hi\x12\x0e\n" +
	"\x02lo\x18\x02 \x01(\x04R\x02lo\"\x81\x02\n" +
	"\x0eBillingCharged\x12B\n" +
	"\vtransfer_id\x18\x01 \x01(\v2!.lurus.events.lugo.v1.TransferRefR\n" +
	"transferId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x128\n" +
	"\x06ledger\x18\x04 \x01(\x0e2 .lurus.events.lugo.v1.LedgerKindR\x06ledger\x12!\n" +
	"\fproduct_code\x18\x05 \x01(\tR\vproductCode\x12\x19\n" +
	"\border_id\x18\x06 \x01(\tR\aorderId\"\x8e\x02\n" +
	"\x0fBillingRefunded\x12B\n" +
	"\vtransfer_id\x18\x01 \x01(\v2!.lurus.events.lugo.v1.TransferRefR\n" +
	"transferId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x128\n" +
	"\x06ledger\x18\x04 \x01(\x0e2 .lurus.events.lugo.v1.LedgerKindR\x06ledger\x12*\n" +
	"\x11original_order_id\x18\x05 \x01(\tR\x0foriginalOrderId\x12\x1c\n" +
	"\x06reason\x18\x06 \x01(\tB\x04\xa0\xbb\x18\x01R\x06reason\"\x9f\x01\n" +
	"\rQuotaDeducted\x12B\n" +
	"\vtransfer_id\x18\x01 \x01(\v2!.lurus.events.lugo.v1.TransferRefR\n" +
	"transferId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x15\n" +
	"\x06ref_id\x18\x04 \x01(\tR\x05refId*Y\n" +
	"\n" +
	"LedgerKind\x12\x1b\n" +
	"\x17LEDGER_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LEDGER_KIND_QUOTA\x10\x01\x12\x17\n" +
	"\x13LEDGER_KIND_CREDITS\x10\x02BGZEgithub.com/hanmahong5-arch/lurus-proto-go/events/lugo/v1;lugoeventsv1b\x06proto3"

var (
	file_lurus_events_lugo_v1_billing_proto_rawDescOnce sync.Once
	file_lurus_events_lugo_v1_billing_proto_rawDescData []byte
)

func file_lurus_events_lugo_v1_billing_proto_rawDescGZIP() []byte {
	file_lurus_events_lugo_v1_billing_proto_rawDescOnce.Do(func() {
		file_lurus_events_lugo_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lurus_events_lugo_v1_billing_proto_rawDesc), len(file_lurus_events_lugo_v1_billing_proto_rawDesc)))
	})
	return file_lurus_events_lugo_v1_billing_proto_rawDescData
}

var file_lurus_events_lugo_v1_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lurus_events_lugo_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lurus_events_lugo_v1_billing_proto_goTypes = []any{
	(LedgerKind)(0),         // 0: lurus.events.lugo.v1.LedgerKind
	(*TransferRef)(nil),     // 1: lurus.events.lugo.v1.TransferRef
	(*BillingCharged)(nil),  // 2: lurus.events.lugo.v1.BillingCharged
	(*BillingRefunded)(nil), // 3: lurus.events.lugo.v1.BillingRefunded
	(*QuotaDeducted)(nil),   // 4: lurus.events.lugo.v1.QuotaDeducted
}
var file_lurus_events_lugo_v1_billing_proto_depIdxs = []int32{
	1, // 0: lurus.events.lugo.v1.BillingCharged.transfer_id:type_name -> lurus.events.lugo.v1.TransferRef
	0, // 1: lurus.events.lugo.v1.BillingCharged.ledger:type_name -> lurus.events.lugo.v1.LedgerKind
	1, // 2: lurus.events.lugo.v1.BillingRefunded.transfer_id:type_name -> lurus.events.lugo.v1.TransferRef
	0, // 3: lurus.events.lugo.v1.BillingRefunded.ledger:type_name -> lurus.events.lugo.v1.LedgerKind
	1, // 4: lurus.events.lugo.v1.QuotaDeducted.transfer_id:type_name -> lurus.events.lugo.v1.TransferRef
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_lurus_events_lugo_v1_billing_proto_init() }
func file_lurus_events_lugo_v1_billing_proto_init() {
	if File_lurus_events_lugo_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lurus_events_lugo_v1_billing_proto_rawDesc), len(file_lurus_events_lugo_v1_billing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lurus_events_lugo_v1_billing_proto_goTypes,
		DependencyIndexes: file_lurus_events_lugo_v1_billing_proto_depIdxs,
		EnumInfos:         file_lurus_events_lugo_v1_billing_proto_enumTypes,
		MessageInfos:      file_lurus_events_lugo_v1_billing_proto_msgTypes,
	}.Build()
	File_lurus_events_lugo_v1_billing_proto = out.File
	file_lurus_events_lugo_v1_billing_proto_goTypes = nil
	file_lurus_events_lugo_v1_billing_proto_depIdxs = nil
}
