// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lurus/events/sync/v1/sync.proto

package synceventsv1

import (
	_ "github.com/hanmahong5-arch/lurus-proto-go/events/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceRegistered: a client device joined a tenant's sync scope.
type DeviceRegistered struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// OS platform: "windows" | "macos" | "linux" | "android" | "ios" | "web".
	Platform   string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	AppVersion string `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	// User-visible device name (e.g. "张三的 iPhone") — routinely contains a
	// person's name, hence PII.
	DeviceName    string `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRegistered) Reset() {
	*x = DeviceRegistered{}
	mi := &file_lurus_events_sync_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRegistered) ProtoMessage() {}

func (x *DeviceRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_sync_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRegistered.ProtoReflect.Descriptor instead.
func (*DeviceRegistered) Descriptor() ([]byte, []int) {
	return file_lurus_events_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceRegistered) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceRegistered) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceRegistered) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *DeviceRegistered) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

// CursorAdvanced: a device acknowledged everything up to a stream sequence.
// Emitted by the sync gateway, consumed by presence/cleanup views. This is a
// fact about consumption progress, NOT the projector-internal cursor (which
// lives in JetStream durable consumer state).
type CursorAdvanced struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// The logical stream whose cursor moved, e.g. "TALLY_EVENTS".
	Stream string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	// Last fully-applied JetStream stream sequence.
	CursorSeq     uint64 `protobuf:"varint,3,opt,name=cursor_seq,json=cursorSeq,proto3" json:"cursor_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorAdvanced) Reset() {
	*x = CursorAdvanced{}
	mi := &file_lurus_events_sync_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorAdvanced) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorAdvanced) ProtoMessage() {}

func (x *CursorAdvanced) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_sync_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorAdvanced.ProtoReflect.Descriptor instead.
func (*CursorAdvanced) Descriptor() ([]byte, []int) {
	return file_lurus_events_sync_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *CursorAdvanced) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CursorAdvanced) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *CursorAdvanced) GetCursorSeq() uint64 {
	if x != nil {
		return x.CursorSeq
	}
	return 0
}

var File_lurus_events_sync_v1_sync_proto protoreflect.FileDescriptor

const file_lurus_events_sync_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x1flurus/events/sync/v1/sync.proto\x12\x14lurus.events.sync.v1\x1a!lurus/events/v1/annotations.proto\"\x93\x01\n" +
	"\x10DeviceRegistered\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x12%\n" +
	"\vdevice_name\x18\x04 \x01(\tB\x04\xa0\xbb\x18\x01R\n" +
	"deviceName\"d\n" +
	"\x0eCursorAdvanced\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x1d\n" +
	"\n" +
	"cursor_seq\x18\x03 \x01(\x04R\tcursorSeqBGZEgithub.com/hanmahong5-arch/lurus-proto-go/events/sync/v1;synceventsv1b\x06proto3"

var (
	file_lurus_events_sync_v1_sync_proto_rawDescOnce sync.Once
	file_lurus_events_sync_v1_sync_proto_rawDescData []byte
)

func file_lurus_events_sync_v1_sync_proto_rawDescGZIP() []byte {
	file_lurus_events_sync_v1_sync_proto_rawDescOnce.Do(func() {
		file_lurus_events_sync_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lurus_events_sync_v1_sync_proto_rawDesc), len(file_lurus_events_sync_v1_sync_proto_rawDesc)))
	})
	return file_lurus_events_sync_v1_sync_proto_rawDescData
}

var file_lurus_events_sync_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lurus_events_sync_v1_sync_proto_goTypes = []any{
	(*DeviceRegistered)(nil), // 0: lurus.events.sync.v1.DeviceRegistered
	(*CursorAdvanced)(nil),   // 1: lurus.events.sync.v1.CursorAdvanced
}
var file_lurus_events_sync_v1_sync_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lurus_events_sync_v1_sync_proto_init() }
func file_lurus_events_sync_v1_sync_proto_init() {
	if File_lurus_events_sync_v1_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lurus_events_sync_v1_sync_proto_rawDesc), len(file_lurus_events_sync_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lurus_events_sync_v1_sync_proto_goTypes,
		DependencyIndexes: file_lurus_events_sync_v1_sync_proto_depIdxs,
		MessageInfos:      file_lurus_events_sync_v1_sync_proto_msgTypes,
	}.Build()
	File_lurus_events_sync_v1_sync_proto = out.File
	file_lurus_events_sync_v1_sync_proto_goTypes = nil
	file_lurus_events_sync_v1_sync_proto_depIdxs = nil
}
