// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lurus/events/tally/v1/stock.proto

package tallyeventsv1

import (
	_ "github.com/hanmahong5-arch/lurus-proto-go/events/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StockReceived: goods entered a warehouse (采购入库/退货入库).
type StockReceived struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SkuId       string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	WarehouseId string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	// Must be > 0.
	Quantity int64 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Unit cost in fen; 0 when unknown at receipt time.
	UnitCostFen int64 `protobuf:"varint,4,opt,name=unit_cost_fen,json=unitCostFen,proto3" json:"unit_cost_fen,omitempty"`
	// Source business document (入库单/采购单) id.
	RefDocId      string `protobuf:"bytes,5,opt,name=ref_doc_id,json=refDocId,proto3" json:"ref_doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockReceived) Reset() {
	*x = StockReceived{}
	mi := &file_lurus_events_tally_v1_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReceived) ProtoMessage() {}

func (x *StockReceived) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_tally_v1_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReceived.ProtoReflect.Descriptor instead.
func (*StockReceived) Descriptor() ([]byte, []int) {
	return file_lurus_events_tally_v1_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockReceived) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *StockReceived) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *StockReceived) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockReceived) GetUnitCostFen() int64 {
	if x != nil {
		return x.UnitCostFen
	}
	return 0
}

func (x *StockReceived) GetRefDocId() string {
	if x != nil {
		return x.RefDocId
	}
	return ""
}

// StockIssued: goods left a warehouse (销售出库/领用出库).
type StockIssued struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SkuId       string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	WarehouseId string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	// Must be > 0; the view subtracts it.
	Quantity      int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	RefDocId      string `protobuf:"bytes,4,opt,name=ref_doc_id,json=refDocId,proto3" json:"ref_doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockIssued) Reset() {
	*x = StockIssued{}
	mi := &file_lurus_events_tally_v1_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockIssued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockIssued) ProtoMessage() {}

func (x *StockIssued) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_tally_v1_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockIssued.ProtoReflect.Descriptor instead.
func (*StockIssued) Descriptor() ([]byte, []int) {
	return file_lurus_events_tally_v1_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockIssued) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *StockIssued) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *StockIssued) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockIssued) GetRefDocId() string {
	if x != nil {
		return x.RefDocId
	}
	return ""
}

// StockTransferred: goods moved between two warehouses of the same tenant.
type StockTransferred struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SkuId           string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	FromWarehouseId string                 `protobuf:"bytes,2,opt,name=from_warehouse_id,json=fromWarehouseId,proto3" json:"from_warehouse_id,omitempty"`
	ToWarehouseId   string                 `protobuf:"bytes,3,opt,name=to_warehouse_id,json=toWarehouseId,proto3" json:"to_warehouse_id,omitempty"`
	// Must be > 0.
	Quantity      int64  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	RefDocId      string `protobuf:"bytes,5,opt,name=ref_doc_id,json=refDocId,proto3" json:"ref_doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockTransferred) Reset() {
	*x = StockTransferred{}
	mi := &file_lurus_events_tally_v1_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockTransferred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockTransferred) ProtoMessage() {}

func (x *StockTransferred) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_tally_v1_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockTransferred.ProtoReflect.Descriptor instead.
func (*StockTransferred) Descriptor() ([]byte, []int) {
	return file_lurus_events_tally_v1_stock_proto_rawDescGZIP(), []int{2}
}

func (x *StockTransferred) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *StockTransferred) GetFromWarehouseId() string {
	if x != nil {
		return x.FromWarehouseId
	}
	return ""
}

func (x *StockTransferred) GetToWarehouseId() string {
	if x != nil {
		return x.ToWarehouseId
	}
	return ""
}

func (x *StockTransferred) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockTransferred) GetRefDocId() string {
	if x != nil {
		return x.RefDocId
	}
	return ""
}

// StockCounted: a physical count fixed the absolute on-hand quantity
// (盘点). Views MUST treat this as an absolute set, not a delta.
type StockCounted struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SkuId       string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	WarehouseId string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	// Absolute on-hand quantity observed by the count; >= 0.
	CountedQuantity int64  `protobuf:"varint,3,opt,name=counted_quantity,json=countedQuantity,proto3" json:"counted_quantity,omitempty"`
	RefDocId        string `protobuf:"bytes,4,opt,name=ref_doc_id,json=refDocId,proto3" json:"ref_doc_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StockCounted) Reset() {
	*x = StockCounted{}
	mi := &file_lurus_events_tally_v1_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockCounted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockCounted) ProtoMessage() {}

func (x *StockCounted) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_tally_v1_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockCounted.ProtoReflect.Descriptor instead.
func (*StockCounted) Descriptor() ([]byte, []int) {
	return file_lurus_events_tally_v1_stock_proto_rawDescGZIP(), []int{3}
}

func (x *StockCounted) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *StockCounted) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *StockCounted) GetCountedQuantity() int64 {
	if x != nil {
		return x.CountedQuantity
	}
	return 0
}

func (x *StockCounted) GetRefDocId() string {
	if x != nil {
		return x.RefDocId
	}
	return ""
}

// StockWrittenOff: stock removed from books (报损/报废).
type StockWrittenOff struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SkuId       string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	WarehouseId string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	// Must be > 0; the view subtracts it.
	Quantity int64 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Human-entered reason (报损原因) — free text can carry person names,
	// hence PII (SCHEMA_RULES R5).
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	RefDocId      string `protobuf:"bytes,5,opt,name=ref_doc_id,json=refDocId,proto3" json:"ref_doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockWrittenOff) Reset() {
	*x = StockWrittenOff{}
	mi := &file_lurus_events_tally_v1_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockWrittenOff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockWrittenOff) ProtoMessage() {}

func (x *StockWrittenOff) ProtoReflect() protoreflect.Message {
	mi := &file_lurus_events_tally_v1_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockWrittenOff.ProtoReflect.Descriptor instead.
func (*StockWrittenOff) Descriptor() ([]byte, []int) {
	return file_lurus_events_tally_v1_stock_proto_rawDescGZIP(), []int{4}
}

func (x *StockWrittenOff) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *StockWrittenOff) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *StockWrittenOff) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockWrittenOff) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StockWrittenOff) GetRefDocId() string {
	if x != nil {
		return x.RefDocId
	}
	return ""
}

var File_lurus_events_tally_v1_stock_proto protoreflect.FileDescriptor

const file_lurus_events_tally_v1_stock_proto_rawDesc = "" +
	"\n" +
	"!lurus/events/tally/v1/stock.proto\x12\x15lurus.events.tally.v1\x1a!lurus/events/v1/annotations.proto\"\xa7\x01\n" +
	"\rStockReceived\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\"\n" +
	"\runit_cost_fen\x18\x04 \x01(\x03R\vunitCostFen\x12\x1c\n" +
	"\n" +
	"ref_doc_id\x18\x05 \x01(\tR\brefDocId\"\x81\x01\n" +
	"\vStockIssued\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x1c\n" +
	"\n" +
	"ref_doc_id\x18\x04 \x01(\tR\brefDocId\"\xb7\x01\n" +
	"\x10StockTransferred\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12*\n" +
	"\x11from_warehouse_id\x18\x02 \x01(\tR\x0ffromWarehouseId\x12&\n" +
	"\x0fto_warehouse_id\x18\x03 \x01(\tR\rtoWarehouseId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x1c\n" +
	"\n" +
	"ref_doc_id\x18\x05 \x01(\tR\brefDocId\"\x91\x01\n" +
	"\fStockCounted\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12)\n" +
	"\x10counted_quantity\x18\x03 \x01(\x03R\x0fcountedQuantity\x12\x1c\n" +
	"\n" +
	"ref_doc_id\x18\x04 \x01(\tR\brefDocId\"\xa3\x01\n" +
	"\x0fStockWrittenOff\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x1c\n" +
	"\x06reason\x18\x04 \x01(\tB\x04\xa0\xbb\x18\x01R\x06reason\x12\x1c\n" +
	"\n" +
	"ref_doc_id\x18\x05 \x01(\tR\brefDocIdBIZGgithub.com/hanmahong5-arch/lurus-proto-go/events/tally/v1;tallyeventsv1b\x06proto3"

var (
	file_lurus_events_tally_v1_stock_proto_rawDescOnce sync.Once
	file_lurus_events_tally_v1_stock_proto_rawDescData []byte
)

func file_lurus_events_tally_v1_stock_proto_rawDescGZIP() []byte {
	file_lurus_events_tally_v1_stock_proto_rawDescOnce.Do(func() {
		file_lurus_events_tally_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lurus_events_tally_v1_stock_proto_rawDesc), len(file_lurus_events_tally_v1_stock_proto_rawDesc)))
	})
	return file_lurus_events_tally_v1_stock_proto_rawDescData
}

var file_lurus_events_tally_v1_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_lurus_events_tally_v1_stock_proto_goTypes = []any{
	(*StockReceived)(nil),    // 0: lurus.events.tally.v1.StockReceived
	(*StockIssued)(nil),      // 1: lurus.events.tally.v1.StockIssued
	(*StockTransferred)(nil), // 2: lurus.events.tally.v1.StockTransferred
	(*StockCounted)(nil),     // 3: lurus.events.tally.v1.StockCounted
	(*StockWrittenOff)(nil),  // 4: lurus.events.tally.v1.StockWrittenOff
}
var file_lurus_events_tally_v1_stock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lurus_events_tally_v1_stock_proto_init() }
func file_lurus_events_tally_v1_stock_proto_init() {
	if File_lurus_events_tally_v1_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lurus_events_tally_v1_stock_proto_rawDesc), len(file_lurus_events_tally_v1_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lurus_events_tally_v1_stock_proto_goTypes,
		DependencyIndexes: file_lurus_events_tally_v1_stock_proto_depIdxs,
		MessageInfos:      file_lurus_events_tally_v1_stock_proto_msgTypes,
	}.Build()
	File_lurus_events_tally_v1_stock_proto = out.File
	file_lurus_events_tally_v1_stock_proto_goTypes = nil
	file_lurus_events_tally_v1_stock_proto_depIdxs = nil
}
